server:
  port: 8081
  use-forward-headers: true

########################################
# spring mvc
########################################
spring:
  application:
    name: Apache Tika
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  sleuth:
    enabled: true
    log:
      slf4j:
        enabled: true
    sampler:
      probability: 1
    web:
      skipPattern: /actuator/.*
  zipkin:
    enabled: true
    baseUrl: ${zipkin.baseurl}
    service:
      name: apache-tika
    sender:
      type: WEB

logging:
  level:
    ROOT: INFO
    org.springframework.boot.autoconfigure.security.reactive: ERROR

management:
  endpoints:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    web:
      exposure:
        include: health, info, metrics, prometheus
  metrics:
    export:
      prometheus:
        enabled: true

scrape_configs:
  - job_name: 'apache-tika'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8081']

zipkin:
  baseurl: http://localhost:9411/